### ISSUE TITLE
Error: I'M A TEAPOT

### ISSUE THREAD

**Issue by ravinpoudel** [ncats/ncats-adme#106]
For some of the molecules i am getting **Error: I'M A TEAPOT** . How to resolve this issues or understand why/what casuse this error?

```
<!doctype html>
<html lang=en>
<title>418 I&#39;m a teapot</title>
<h1>I&#39;m a teapot</h1>
<p>There was an unknown error.</p>


```

<img width="873" alt="Screenshot 2023-12-18 at 1 47 52 PM" src="https://github.com/ncats/ncats-adme/assets/25137267/a7625ada-c27d-4dfb-91bb-34bb7deda7c2">

**Comment by iwwwish** [comment]
Hi @ravinpoudel

There seems to be an issue with the `cyp450` models. The API calls should work for the rest of the models though. We are looking into this right now and will update here when we fix the issue.

Best,
Vishal

**Comment by ravinpoudel** [comment]
@iwwwish Hi Vishal, Thanks for the quick response. Looking forward to the solution.

**Comment by ravinpoudel** [comment]
@iwwwish  I am also getting error for pampabbb 
Smiles: C=C(NC(=O)C(C)NC(=O)CNC(=O)C(NC(=O)C1CSCC(NC(=O)C(=C)NC(=O)C(CC(N)=O)NC(=O)C(NC(=O)C(NC(=O)C(CO)NC(=O)C(CCCCN)NC(=O)C(CO)NC(=O)C(NC(=O)C(NC(=O)C2CSCC(N)C(=O)NC(=C)C(=O)NC(C(C)C)C(=O)NC(C)C(=O)NC(CCCCN)C(=O)NC(=CC)C(=O)NC(C(C)C)C(=O)N2)C(C)C)C(C)C)C(C)C)C(C)C)C(=O)NC(CCCCN)C(=O)NC(C(C)C)C(=O)N1)C(C)CC)C(=O)NC(CC(C)C)C(=O)NC1CSCC(C(=O)O)NC(=O)C(CCC(=O)O)NC(=O)C(CCCCN)NC(=O)C(CC(N)=O)NC(=O)C(Cc2ccc(O)cc2)NC(=O)C(=C)NC(=O)C(Cc2ccccc2)NC(=O)C(C(C)CC)NC(=O)CNC(=O)C(CO)NC(=O)C(C(C)CC)NC(=O)C(C)NC1=O
<img width="794" alt="Screenshot 2023-12-20 at 5 31 45 PM" src="https://github.com/ncats/ncats-adme/assets/25137267/cccaf463-e271-4d0a-abaa-233ee4d8ecca">

**Comment by iwwwish** [comment]
Hi Ravin,

I am not 100% sure but if it is only for pampa-bbb then, given the complex
nature of the molecule, it might most likely be an RDKit descriptor
calculation error because only the pampa-bbb and cyp450 models rely on
RDKit descriptors. Also, we do not usually display the error traces as they
could get really long sometimes which is why you see the generic Teapot
error thrown in such instances. Will try to look into this and have a fix
soon.

Best,
Vishal

**Comment by iwwwish** [comment]
Hi @ravinpoudel

The issue with CYP models has been fixed by the team. The API should work now for all models. I have tried the molecule you used in your first question: `O=c1cc(N2CCCOCC2)oc2c1ccc1ccccc12` and you can see the result below. For the second molecule, I believe the error is indeed during RDKit descriptor calculation as it only fails when PAMPA BBB model is selected. Hope this helps. I will close the issue for now but please feel free to reopen if you have this or any other issue.

Best,
Vishal

<img width="766" alt="API example" src="https://github.com/ncats/ncats-adme/assets/5487952/51a530a4-1ce2-436a-b695-967768c5e2d8">
