### ISSUE TITLE
ResolvePackageNotFound:   - gunicorn

### ISSUE THREAD

**Issue by jaidev233** [ncats/ncats-adme#56]
On windows system, when we try to resolve environment using conda, following error shows up

ResolvePackageNotFound:
  - gunicorn

**Comment by iwwwish** [comment]
Hi @jaidev233! Sorry for the delay in responding. This issue was fixed in #60. Gunicorn is not available for Windows operating system from [anaconda](https://anaconda.org/anaconda/gunicorn). The package was removed from conda dependencies and added to the pip requirements. We could use the [new environment file](https://github.com/ncats/ncats-adme/blob/master/server/environment.yml) on Windows 10 for successful creation on the conda environment. Also, the app is currently launched via 'python app.py' rather than via gunicorn. We will eventually get rid of gunicorn dependency.

**Comment by jaidev233** [comment]
Hi vishal

thanks for getting back to me, i actually found a work around by using, WSL
for windows, could work as a patch work.

Thanks for the update

Jaidev Sharma

**Comment by iwwwish** [comment]
Hi Jaidev! I'm glad you found a workaround. We might just get rid of gunicorn in our next release. There will not be any performance issues because the number of workers in gunicorn configuration has always been 1. However, please feel free to share your patch. Thanks!

Vishal

**Comment by iwwwish** [comment]
Closing due to lack of response.
