### ISSUE TITLE
setting up local version

### ISSUE THREAD

**Issue by onexhale** [ncats/ncats-adme#70]
Apologies - chemist with a little computer knowledge rather than the other way around. I have been attempting to set up local version, however when running app.py as described I get an error. As far as I can tell from init.py the script is attempting to download model files that are no longer on tripod.nih.gov ( eg rf_morgan_all_data.pkl from https://tripod.nih.gov/pub/adme/models/rlm/ ). Is this the case, if so is there a workaround?

**Comment by iwwwish** [comment]
Hello @onexhale,

Unfortunately, the master branch is not current. Could you please download the latest code from development branch and give it a try? We will push code to master in our next release along with a few more updates. Also, all RLM models except the one based on GCNN were taken off the website since we decided to host only the best model as we kept adding new endpoints (e.g. PAMPA, SOL, HLC etc.) - this is why the older model files were deleted from tripod.nih.gov. You could see that we now load only the gcnn model from the [latest init.py](https://github.com/ncats/ncats-adme/blob/development/server/predictors/rlm/__init__.py) for RLM predictor.

Please let me know how it does with the code from development branch?

Best,
Vishal

**Comment by onexhale** [comment]
Hi @iwwwish ,

Thanks for the quick reply, I have followed this up and can confirm the code and models from the dev branch appear to be working fine here. 

Cheers, Scott
