### ISSUE TITLE
Failure to run the app.py file

### ISSUE THREAD

**Issue by pauline-banye** [ncats/ncats-adme#73]
Hi @iwwwish, I'm encountering an error while trying to run the application.

### Error encountered while executing the python app.py command
Whenever I try to run `python app.py`, I get `_pickle.UnpicklingError: invalid load key, '<'.` error

![ncat](https://user-images.githubusercontent.com/63536707/208537641-e578c8eb-7b80-4cc1-b397-7a8fe6455431.png)

### Operating System
- WSL on Windows 10
- Python 3.8.13
- Anaconda 4.14.0

### Steps I took

- [x] Installed Anaconda 
- [x] Cloned the repo `git clone --recursive https://github.com/ncats/ncats-adme.git`
- [x]  cd ADME-NCATS
- [x] Created environment `conda env create --prefix ./env -f environment.yml`
- [x] Executed the `pip install typed-argument-parser` command
- [x] Activated environment `conda activate ./env`
- [ ] Got the above error when running command `python app.py`

**Comment by iwwwish** [comment]
Hello @pauline-banye,

Sorry that you could not get the `app.py` file running. The error you see occurs when the code is trying to load the random forest model for RLM endpoint but fails to do so. We discontinued all RLM models (such as random forest and deep neural network) except the one based on graph convolutional neural network. So, the corresponding pickle files were taken off the website where we host the models.

Due to a recent security incident, the `master` branch was rolled back to a previous version of our code. Could you give it another try by downloading the code from `development` branch with the latest code? We will update the `master` branch very soon.

To clone development branch, run this: `git clone --recursive -b development https://github.com/ncats/ncats-adme.git`

I'll be pleased to know how it goes. Thanks!

Vishal

**Comment by pauline-banye** [comment]
> git clone --recursive -b development https://github.com/ncats/ncats-adme.git

Thanks for your swift response @iwwwish , cloning now and I would definitely provide an update

**Comment by pauline-banye** [comment]
Hi @iwwwish  I have been able to run `python app.py` but it seems to end up with a connection error after a while, due to the internet connection I guess. I have downloaded the models from the links shared, could you tell me where to place them?

**Comment by iwwwish** [comment]
Could you share the exact error you get after running `python app.py`? Is it related to loading the model files? If you want to place the model files within the cloned repo yourselves, they would go into this directory: `ncats-adme/server/models`.

**Comment by pauline-banye** [comment]
> Could you share the exact error you get after running `python app.py`? Is it related to loading the model files? If you want to place the model files within the cloned repo yourselves, they would go into this directory: `ncats-adme/server/models`.

Hi @iwwwish it's a connection timeout error which usually occurs whilst downloading the CYP450 model. I'll run it again and send a screenshot. 

Meanwhile I had a look at the contents of the ncat-adme/server/model folder and all I saw was the gcnn_model.pt but the database has model 0 - 63, do I place them in the ncat-adme/server/model and delete the gcnn_model.pt file?

**Comment by iwwwish** [comment]
So, all individual models should go within `ncats-adme/server/models/` in the exact same structure as they are [here](https://tripod.nih.gov/pub/adme/models/). For example:

1. RLM model would take this path: `ncats-adme/server/models/rlm/gcnn_model.pt`
2. CYP450 3A4 inhibition models would take this path: `ncats-adme/server/models/CYP450/CYP3A4_inhib/model_X`, where X is 0 to 63.

I think manually downloading individual files could be a pain. It would be much easier if you could get the code to load them for you.

**Comment by iwwwish** [comment]
@pauline-banye I am closing the issue for now. If you still have issues with loading the models, please feel free to reopen this.

**Comment by frank-stonybrook** [comment]
I also have a hard time deploying the current master branch ([52f968f](https://github.com/ncats/ncats-adme/commit/52f968f598cefba70b083139e8faf87f4b5c4731)). So I followed your previous suggestion cloning the development branch and installed necessary 3rd-party python modules. 

The server ran nicely but the PAMPA74 prediction seems incorrect. I validate using those high permeable compounds from your [paper](https://journals.sagepub.com/doi/full/10.1177/24725552211017520). All of them are predicted to be "low or moderate". 

Attached are the compounds used for testing: [high_permeable_compds.txt](https://github.com/ncats/ncats-adme/files/10865015/high_permeable_compds.txt)

Thanks!

**Comment by iwwwish** [comment]
Hi Frank! Thanks for reporting this issue. After the last update (models only), the predictions are affected due to a Python library version mismatch. This is why we have taken down our website temporarily. Long story short - we recently switched to an automated pipeline to update the models and this pipeline uses a newer version of a library compared to the version used in the production environment. We will fix this issue soon.

Meanwhile, you could use the most recent model files that are available in our archive. Note that once you place them into corresponding model directories, you will need to rename the model files to `gcnn_model.pt`, e.g. for RLM model the path is `~/ncats-adme/server/models/rlm/gcnn_model.pt`.

Links to archived models:

1. RLM - https://opendata.ncats.nih.gov/public/adme/models/archived/rlm/gcnn_model-20230201.pt
2. PAMPA 7.4 - https://opendata.ncats.nih.gov/public/adme/models/archived/pampa/gcnn_model-20230201.pt
3. SOL - https://opendata.ncats.nih.gov/public/adme/models/archived/solubility/gcnn_model-20230201.pt

I hope this helps.

Best,
Vishal

**Comment by iwwwish** [comment]
Yes! The master branch is a bit more stable but does not cover most recent UI ad model updates which are only available from development. Once the library issue is sorted we will merge everything into master and make the website live again.
