### ISSUE TITLE
Conda env cannot be created with the provided yml file

### ISSUE THREAD

**Issue by ravinpoudel** [ncats/ncats-adme#96]
I am on the mac (M1), and getting following error. Any suggestion on how to fix the issues? 

```➜  server git:(master) ✗ conda env create --prefix ./env -f environment_mac.yml
Collecting package metadata (repodata.json): | WARNING conda.models.version:get_matcher(535): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(535): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
done
Solving environment: failed

ResolvePackageNotFound:
  - pytorch=1.6.0
  - rdkit=2020.03
  - torchvision=0.7.0
  - scikit-learn=0.22
  - numpy=1.18
  - efelix::fpsim2=0.2.6
  - matplotlib=3.3.0```

**Comment by iwwwish** [comment]
Hi @ravinpoudel,

Sorry for the delay in responding. One of the key issues with installing our environment on a M1 Mac is getting to install tensorflow. Apple has [special instructions](https://developer.apple.com/metal/tensorflow-plugin/) to install tensorflow on MacBooks with silicon or AMD GPUs. However, since our current models do not directly rely on tensorflow, I have removed tensorflow and a couple of other related packages from the environment file. Please try installing the environment with [this environment file](https://gist.github.com/iwwwish/2805bda52d9e0185d581401f076e64d0) using the following command:

`conda env create -f environment_mac_M1.yml`

Let me know if it works so that I can update the README on the git repo. I have tested the file on my M1 Mac and it worked fine.

Best,
Vishal
